spring:
  application:
    name: GameAnalytics
  datasource:
    url: jdbc:postgresql://localhost:5432/game
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: false
    generate-ddl: false
  sql:
    init:
      platform: postgresql


  liquibase:
    change-log: classpath:db/changelog/master.yaml
    enabled: true
